source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

xcodeproj 'PVGTableViewProxyExample'
workspace '../PVGTableViewProxy'
inhibit_all_warnings!
use_frameworks!

target 'PVGTableViewProxyExample', :exclusive => true do
  pod "PVGTableViewProxy", :path => "../"
end
