source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

project 'PVGTableViewProxyExample'
workspace '../PVGTableViewProxy'
inhibit_all_warnings!
use_frameworks!

target 'PVGTableViewProxyExample' do
  pod "PVGTableViewProxy", :path => "../"
end
