source 'https://github.com/CocoaPods/Specs'
platform :ios, '8.0'

project 'PVGTableViewProxyTests'
workspace '../PVGTableViewProxy'
inhibit_all_warnings!
use_frameworks!

target 'Tests' do
  pod 'OCMock', '3.2'
  pod 'ReactiveCocoa', '4.1.0'
  pod 'PVGTableViewProxy', :path => '../'
end

