source 'https://github.com/CocoaPods/Specs'

xcodeproj 'PVGTableViewProxyTests'
workspace '../PVGTableViewProxy'
inhibit_all_warnings!
use_frameworks!

target :ios do
  platform :ios, '8.0'
  link_with 'Tests'

  pod 'OCMock', '3.2'
  pod 'ReactiveCocoa', '4.1.0'
  pod 'PVGTableViewProxy', :path => '../'
end

