source 'https://github.com/CocoaPods/Specs'

xcodeproj 'PVGTableViewProxyTests'
workspace '../PVGTableViewProxy'
inhibit_all_warnings!

target :ios do
  platform :ios, '7.0'
  link_with 'Tests'

  pod 'OCMock', '3.2.0'
  pod 'ReactiveCocoa', '2.4.2'
  pod 'PVGTableViewProxy', :path => '../'
end

